version: "3.9"

# Use this file for an example for production

services:
  db:
    image: mariadb:10.4
    restart: unless-stopped 
    stdin_open: true
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ITOP_DB_NAME}
      - MYSQL_USER=${ITOP_DB_USER}
      - MYSQL_PASSWORD=${ITOP_DB_PASS}
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  itop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - PHP_TIMEZONE=${PHP_TIMEZONE}
      - PHP_ENABLE_UPLOADS=${PHP_ENABLE_UPLOADS}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME}
      - PHP_LOG_ERRORS=${PHP_LOG_ERRORS}
      - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING}

#    image: vbkunin/itop:2.7.4-base
    restart: unless-stopped
    stdin_open: true
    networks:
      - mynetwork
    environment:
      - ITOP_DB_HOST=${ITOP_DB_HOST}
      - ITOP_DB_NAME=${ITOP_DB_NAME}
      - ITOP_DB_USER=${ITOP_DB_USER}
      - ITOP_DB_PASS=${ITOP_DB_PASS}
      - PHP_TIMEZONE=${PHP_TIMEZONE}
      - PHP_ENABLE_UPLOADS=${PHP_ENABLE_UPLOADS}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME}
      - PHP_LOG_ERRORS=${PHP_LOG_ERRORS}
      - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING}
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./volumes/itop/conf:/var/www/itop/conf
      - ./volumes/itop/data:/var/www/itop/data
      - ./volumes/itop/log:/var/www/itop/log
      - ./volumes/itop/env-production:/var/www/itop/env-production
      - ./volumes/itop/env-production-build:/var/www/itop/env-production-build
      - ./extensions:/var/www/itop/extensions
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  adminer:
    image: adminer
    restart: unless-stopped
    stdin_open: true
    networks:
      - mynetwork
    links:
      - db
    ports:
      - "8000:8080"

networks:
  mynetwork:
    driver: bridge

