version: "3"

# Use this file for an example for production

services:
  db:
    image: mariadb:10.4
    restart: unless-stopped 
    stdin_open: true
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iop
      - MYSQL_DATABASE=itop
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  itop:
    build:
      context: .
      dockerfile: Dockerfile
#    image: vbkunin/itop:2.7.4-base
    restart: unless-stopped
    stdin_open: true
    networks:
      - mynetwork
    environment:
      - ITOP_DB_HOST=db
      - ITOP_DB_NAME=itop
      - ITOP_DB_USER=itop
      - ITOP_DB_PASS=itop
      - PHP_TIMEZONE="Europe/Paris"
      - PHP_ENABLE_UPLOADS="On"
      - PHP_MEMORY_LIMIT="256M"
      - PHP_POST_MAX_SIZE="10M"
      - PHP_UPLOAD_MAX_FILESIZE="8M"
      - PHP_MAX_FILE_UPLOADS="20"
      - PHP_MAX_INPUT_TIME="300"
      - PHP_LOG_ERRORS="On"
      - PHP_ERROR_REPORTING="E_ALL" # Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./volumes/itop/conf:/var/www/itop/conf
      - ./volumes/itop/data:/var/www/itop/data
      - ./volumes/itop/log:/var/www/itop/log
      - ./volumes/itop/env-production:/var/www/itop/env-production
      - ./volumes/itop/env-production-build:/var/www/itop/env-production-build
      - ./extensions:/var/www/itop/extensions
  adminer:
    image: adminer
    restart: unless-stopped
    stdin_open: true
    networks:
      - mynetwork
    links:
      - db
    ports:
      - "8000:8080"

networks:
  mynetwork:
    driver: bridge

